#include "elf_skill.h"
std::map<QString, int> skillNameMap = {
    {"生机", 0},
    {"毒药", 1},
    {"打火机", 2},
    {"冰箱", 3},
    {"埋土里", 4},
    {"麻痹", 5},
    {"手术刀", 6},
    {"枯萎", 7},
    {"激素", 8},
    {"强健", 9},
    {"风之庇佑", 10},
    {"金钟罩", 11},
    {"石化", 12},
    {"森林", 13},
    {"水泡", 14},
    {"光合作用", 15},
    {"川流不息", 16},
    {"生生不息", 17},
    {"大地之母的庇佑", 18},
    {"金汤肥牛", 19},
    {"雷池", 20},
    {"沼泽", 21},
    {"漩涡", 22},
    {"蓝银缠绕", 23},
    {"火之翼", 24},
    {"水之翼", 25},
    {"金之翼", 26},
    {"电之翼", 27},
    {"风之翼", 28},
    {"爆炸", 29},
    {"冰冻", 30},
    {"千钧", 31},
    {"雷击", 32},
    {"陨石", 33},
    {"中毒", 34},
    {"虚弱", 35},
    {"流血", 36},
    {"风刃", 37},
    {"蓄意轰拳", 38}
};

elf_skill skills[] = {
    elf_skill("生机", 0, 60, Attribute::木, buffs[(int)BuffType::HEAL], 0, 1.0),
    elf_skill("毒药", 0, 30, Attribute::木, buffs[(int)BuffType::POISON], 1, 1.0),
    elf_skill("打火机", 0, 60, Attribute::火, buffs[(int)BuffType::BURN], 1, 1.0),
    elf_skill("冰箱", 0, 60, Attribute::水, buffs[(int)BuffType::FREEZE], 1, 1.0),
    elf_skill("埋土里", 0, 60, Attribute::土, buffs[(int)BuffType::STUN], 1, 1.0),
    elf_skill("麻痹", 0, 60, Attribute::电, buffs[(int)BuffType::PARALYSIS], 1, 1.0),
    elf_skill("手术刀", 0, 60, Attribute::金, buffs[(int)BuffType::BLEED], 1, 1.0),
    elf_skill("枯萎", 0, 60, Attribute::木, buffs[(int)BuffType::WEAK], 1, 1.0),
    elf_skill("激素", 0, 60, Attribute::无, buffs[(int)BuffType::HORMONE], 0, 1.0),
    elf_skill("强健", 0, 60, Attribute::无, buffs[(int)BuffType::BUILDUP], 0, 1.0),
    elf_skill("风之庇佑", 0, 60, Attribute::木, buffs[(int)BuffType::WIND], 0, 1.0),
    elf_skill("金钟罩", 0, 60, Attribute::金, buffs[(int)BuffType::STONE], 0, 1.0),
    elf_skill("石化", 0, 60, Attribute::土, buffs[(int)BuffType::STONE], 0, 1.0),
    elf_skill("森林", 0, 60, Attribute::木, buffs[(int)BuffType::STONE], 0, 1.0),
    elf_skill("水泡", 0, 60, Attribute::水, buffs[(int)BuffType::STONE], 0, 1.0),
    elf_skill("光合作用", 0, 60, Attribute::木, buffs[(int)BuffType::SPRING], 0, 1.0),
    elf_skill("川流不息", 0, 60, Attribute::水, buffs[(int)BuffType::SPRING], 0, 1.0),
    elf_skill("生生不息", 0, 60, Attribute::火, buffs[(int)BuffType::SPRING], 0, 1.0),
    elf_skill("大地之母的庇佑", 0, 60, Attribute::土, buffs[(int)BuffType::SPRING], 0, 1.0),
    elf_skill("金汤肥牛", 0, 60, Attribute::金, buffs[(int)BuffType::SPRING], 0, 1.0),
    elf_skill("雷池", 0, 60, Attribute::电, buffs[(int)BuffType::SPRING], 0, 1.0),
    elf_skill("沼泽", 0, 60, Attribute::土, buffs[(int)BuffType::SLOWDOWN], 1, 1.0),
    elf_skill("漩涡", 0, 60, Attribute::水, buffs[(int)BuffType::SLOWDOWN], 1, 1.0),
    elf_skill("蓝银缠绕", 0, 60, Attribute::木, buffs[(int)BuffType::SLOWDOWN], 1, 1.0),
    elf_skill("火之翼", 0, 60, Attribute::火, buffs[(int)BuffType::FLY], 0, 1.0),
    elf_skill("水之翼", 0, 60, Attribute::水, buffs[(int)BuffType::FLY], 0, 1.0),
    elf_skill("金之翼", 0, 60, Attribute::金, buffs[(int)BuffType::FLY], 0, 1.0),
    elf_skill("电之翼", 0, 60, Attribute::电, buffs[(int)BuffType::FLY], 0, 1.0),
    elf_skill("风之翼", 0, 60, Attribute::木, buffs[(int)BuffType::FLY], 0, 1.0),
    elf_skill("爆炸", 120, 60, Attribute::火, buffs[(int)BuffType::BURN], 1, 0.2),
    elf_skill("冰冻", 120, 60, Attribute::水, buffs[(int)BuffType::FREEZE], 1, 0.2),
    elf_skill("千钧", 120, 60, Attribute::金, buffs[(int)BuffType::STUN], 1, 0.2),
    elf_skill("雷击", 120, 60, Attribute::电, buffs[(int)BuffType::PARALYSIS], 1, 0.2),
    elf_skill("陨石", 120, 60, Attribute::土, buffs[(int)BuffType::STUN], 1, 0.2),
    elf_skill("中毒", 120, 60, Attribute::木, buffs[(int)BuffType::POISON], 1, 0.2),
    elf_skill("虚弱", 120, 60, Attribute::木, buffs[(int)BuffType::WEAK], 1, 0.2),
    elf_skill("流血", 120, 60, Attribute::金, buffs[(int)BuffType::BLEED], 1, 0.2),
    elf_skill("风刃", 120, 60, Attribute::木, buffs[(int)BuffType::WIND], 0, 0.2),
    elf_skill("蓄意轰拳", 150, 60, Attribute::无, Buff(), 1, 0),

};
